version: '2'
services:
    devitwithgregwebsite-mongodb:
        image: mongo:3.2.10
        ports:
            - "27017:27017"
        command: mongos --configdb devitwithgregwebsite-mongodb-config
    devitwithgregwebsite-mongodb-node:
        build:
            context: .
            dockerfile: mongodb/MongoDB.Dockerfile
        command: mongod --replSet rs1 --noprealloc --smallfiles
    devitwithgregwebsite-mongodb-config:
        image: mongo:3.2.10
        container_name: devitwithgregwebsite-mongodb-config
        command: mongod --noprealloc --smallfiles --configsvr --dbpath /data/db
